"""empty message

Revision ID: 1e94af5397ba
Revises: None
Create Date: 2014-06-03 21:57:50.317345

"""

# revision identifiers, used by Alembic.
revision = '1e94af5397ba'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('zipcode', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('zipcode')
    )
    op.create_table('Hardware',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('HardwareModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('hardware_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hardware_id'], ['Hardware.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('County',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('hardware_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hardware_id'], ['Hardware.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('System',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('managementip', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('hardware_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hardware_id'], ['Hardware.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('managementip'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('hardware_id', sa.Integer(), nullable=True),
    sa.Column('hardware_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hardware_id'], ['Hardware.id'], ),
    sa.ForeignKeyConstraint(['hardware_model_id'], ['HardwareModel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('hardware_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['County.id'], ),
    sa.ForeignKeyConstraint(['hardware_id'], ['Hardware.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('L2Domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['System.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('SystemCategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['System.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('HardwareType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('hardware_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hardware_model_id'], ['HardwareModel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('HardwareType')
    op.drop_table('SystemCategory')
    op.drop_table('L2Domain')
    op.drop_table('Country')
    op.drop_table('Vendor')
    op.drop_table('System')
    op.drop_table('County')
    op.drop_table('HardwareModel')
    op.drop_table('Hardware')
    op.drop_table('Address')
    ### end Alembic commands ###
