"""empty message

Revision ID: 1e9725c07514
Revises: 4fdf79a6d393
Create Date: 2014-06-25 21:56:58.124070

"""

# revision identifiers, used by Alembic.
revision = '1e9725c07514'
down_revision = '4fdf79a6d393'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
