"""empty message

Revision ID: 21921b433023
Revises: 55ca4442eb0d
Create Date: 2014-06-25 22:36:29.172243

"""

# revision identifiers, used by Alembic.
revision = '21921b433023'
down_revision = '55ca4442eb0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
