"""empty message

Revision ID: 27ee6a1d9fe0
Revises: 395191b8a397
Create Date: 2014-06-25 17:32:29.542836

"""

# revision identifiers, used by Alembic.
revision = '27ee6a1d9fe0'
down_revision = '395191b8a397'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Street',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('street_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['street_id'], ['Street.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('City',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['County.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('City')
    op.drop_table('Street')
    ### end Alembic commands ###
