"""empty message

Revision ID: 2c91dd37e356
Revises: 21921b433023
Create Date: 2014-06-27 17:36:44.073722

"""

# revision identifiers, used by Alembic.
revision = '2c91dd37e356'
down_revision = '21921b433023'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    ### end Alembic commands ###
