"""empty message

Revision ID: 395191b8a397
Revises: None
Create Date: 2014-06-24 22:37:26.169146

"""

# revision identifiers, used by Alembic.
revision = '395191b8a397'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('L2Domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('zipcode', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('zipcode')
    )
    op.create_table('Vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('HardwareType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('County',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['Country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['Vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('HardwareModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('hardware_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hardware_type_id'], ['HardwareType.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['Vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('SoftwareVersion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['software_id'], ['Software.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Hardware',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('asset_tag', sa.String(length=64), nullable=True),
    sa.Column('hardware_model_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['hardware_model_id'], ['HardwareModel.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['Vendor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_tag'),
    sa.UniqueConstraint('name')
    )
    op.create_table('System',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('management_ip', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('l2domain_id', sa.Integer(), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.Column('software_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['l2domain_id'], ['L2Domain.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['Software.id'], ),
    sa.ForeignKeyConstraint(['software_version_id'], ['SoftwareVersion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('management_ip'),
    sa.UniqueConstraint('name')
    )
    op.create_table('systems_hardware',
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('hardware_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hardware_id'], ['Hardware.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['System.id'], )
    )
    op.create_table('SystemCategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['System.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SystemCategory')
    op.drop_table('systems_hardware')
    op.drop_table('System')
    op.drop_table('Hardware')
    op.drop_table('SoftwareVersion')
    op.drop_table('HardwareModel')
    op.drop_table('Software')
    op.drop_table('County')
    op.drop_table('HardwareType')
    op.drop_table('Vendor')
    op.drop_table('Address')
    op.drop_table('Country')
    op.drop_table('L2Domain')
    ### end Alembic commands ###
