"""empty message

Revision ID: 47ec80f9dea9
Revises: 2c91dd37e356
Create Date: 2014-06-27 19:56:30.514664

"""

# revision identifiers, used by Alembic.
revision = '47ec80f9dea9'
down_revision = '2c91dd37e356'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User')
    op.create_unique_constraint(u'user_name', 'User', ['user_name'])
    op.add_column('User', sa.Column('user_name', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('User', 'name')
    ### end Alembic commands ###
