"""empty message

Revision ID: 4cef3dfa3d7c
Revises: 27ee6a1d9fe0
Create Date: 2014-06-25 17:33:49.653679

"""

# revision identifiers, used by Alembic.
revision = '4cef3dfa3d7c'
down_revision = '27ee6a1d9fe0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('Street', 'street_id')
    #op.drop_column('Street', sa.Column('city_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('Street', sa.Column('street_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    #op.drop_column('Street', 'city_id')
    ### end Alembic commands ###
    pass
