"""empty message

Revision ID: 547f7075ec95
Revises: 39d73b791c9a
Create Date: 2014-06-25 19:03:34.033535

"""

# revision identifiers, used by Alembic.
revision = '547f7075ec95'
down_revision = '39d73b791c9a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Location')
    op.create_table('Location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('zipcode', sa.String(length=64), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('street_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['City.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['Country.id'], ),
    sa.ForeignKeyConstraint(['county_id'], ['County.id'], ),
    sa.ForeignKeyConstraint(['street_id'], ['Street.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('zipcode')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Street', sa.Column('street_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_table('Address',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('zipcode', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('Location')
    ### end Alembic commands ###
