"""empty message

Revision ID: 55ca4442eb0d
Revises: 77254c34c94
Create Date: 2014-06-25 22:32:31.719841

"""

# revision identifiers, used by Alembic.
revision = '55ca4442eb0d'
down_revision = '77254c34c94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Hardware', sa.Column('hardware_type_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Hardware', 'hardware_type_id')
    ### end Alembic commands ###
