"""empty message

Revision ID: 77254c34c94
Revises: fa7d41b7d13
Create Date: 2014-06-25 22:26:16.978083

"""

# revision identifiers, used by Alembic.
revision = '77254c34c94'
down_revision = 'fa7d41b7d13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Hardware', sa.Column('coordinance', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'Hardware', ['coordinance'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Hardware')
    op.drop_column('Hardware', 'coordinance')
    ### end Alembic commands ###
