"""empty message

Revision ID: fa7d41b7d13
Revises: 1e9725c07514
Create Date: 2014-06-25 22:18:15.338369

"""

# revision identifiers, used by Alembic.
revision = 'fa7d41b7d13'
down_revision = '1e9725c07514'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('System', sa.Column('location_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('System', 'location_id')
    ### end Alembic commands ###
