"""empty message

Revision ID: fd950e79635
Revises: 4cef3dfa3d7c
Create Date: 2014-06-25 18:12:46.240060

"""

# revision identifiers, used by Alembic.
revision = 'fd950e79635'
down_revision = '4cef3dfa3d7c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('Street', 'city_id')
    #op.drop_column('Street', 'street_id')
    ### end Alembic commands ###
    op.add_column('Street', sa.Column('city_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Street', sa.Column('street_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('Street', sa.Column('city_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
